controllers/PublicationController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Publication;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PublicationController implements the CRUD actions for Publication model.
 */
class PublicationController extends Controller
{
    /**
     * @inheritdoc
     */
    public $apelido = 'noticia';
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Publication models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Publication::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Publication model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Publication model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Publication();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Publication model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Publication model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Publication model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Publication the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Publication::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }


}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Url;

$this->title = 'Bee news - Site de notícias';
$slider_publications = \app\models\Publication::find()->orderBy(['id'=> SORT_DESC])->limit(3)->all();
$side_publications = $slider_publications;
?>
<!-- Trending post start -->
<section class="featured-post-area no-padding">
    <div class="container">
        <div class="row">
            <!-- Main Publications -->
            <div class="col-md-7 col-xs-12 pad-r">
                <div id="featured-slider" class="owl-carousel owl-theme featured-slider">
                    <?php foreach ($slider_publications as $publication){ ?>
                        <div class="item" style="background-image:url(images/news/lifestyle/health5.jpg)">
                            <div class="featured-post">
                                <div class="post-content">
                                    <a class="post-cat" href="#"><?=$publication->category->name?></a>
                                    <h2 class="post-title title-extra-large">
                                        <a href="<?=Url::to(['publication/view', 'id'=>$publication->id])?>"><?=$publication->title?></a>
                                    </h2>
                                    <span class="post-date"></span>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                </div><!-- Featured owl carousel end-->
            </div><!-- Col 7 end -->
            <!-- Main Publications End -->

            <!-- Others Publications -->
            <div class="col-md-5 col-xs-12 pad-l">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="post-overaly-style contentTop hot-post-top clearfix">
                            <div class="post-thumb">
                                <a href=""><img class="img-responsive" src="images/news/tech/gadget4.jpg" alt="" /></a>
                            </div>
                            <div class="post-content">
                                <a class="post-cat" href="#"><?= $side_publications[0]->category->name?></a>
                                <h2 class="post-title title-large">
                                    <a href="<?=Url::to(['publication/view', 'id'=>$side_publications[0]->id])?>"><?= $side_publications[0]->title?></a>
                                </h2>
                                <span class="post-date"><?= $side_publications[0]->pub_date ?></span>
                            </div><!-- Post content end -->
                        </div><!-- Post Overaly end -->
                    </div><!-- Col end -->

                    <div class="col-sm-6 pad-r-small">
                        <div class="post-overaly-style contentTop hot-post-bottom clearfix">
                            <div class="post-thumb">
                                <a href="#"><img class="img-responsive" src="images/news/lifestyle/travel2.jpg" alt="" /></a>
                            </div>
                            <div class="post-content">
                                <a class="post-cat" href="#"><?=$side_publications[1]->category->name?></a>
                                <h2 class="post-title title-medium">
                                    <a href="<?=Url::to(['publication/view', 'id'=>$side_publications[1]->id])?>"><?=$side_publications[1]->title?></a>
                                </h2>
                            </div><!-- Post content end -->
                        </div><!-- Post Overaly end -->
                    </div><!-- Col end -->

                    <div class="col-sm-6 pad-l-small">
                        <div class="post-overaly-style contentTop hot-post-bottom clearfix">
                            <div class="post-thumb">
                                <a href="#"><img class="img-responsive" src="images/news/lifestyle/health1.jpg" alt="" /></a>
                            </div>
                            <div class="post-content">
                                <a class="post-cat" href="#"><?=$side_publications[2]->category->name?></a>
                                <h2 class="post-title title-medium">
                                    <a href="<?=Url::to(['publication/view', 'id'=>$side_publications[2]->id])?>"><?=$side_publications[2]->title?></a>
                                </h2>
                            </div><!-- Post content end -->
                        </div><!-- Post Overaly end -->
                    </div><!-- Col end -->
                </div>
            </div><!-- Col 5 end -->
            <!-- Others Publications End -->


        </div><!-- Row end -->
    </div><!-- Container end -->
</section>
<!-- Trending post end -->

<?php
    $categories = \app\models\Category::find()->limit(3)->all();

?>
<!-- 2nd block starts -->
<section class="block-wrapper">
    <div class="container">
        <div class="row">

            <?php foreach ($categories as $category){?>
            <div class="col-md-4">
                <div class="block <?= $category->color ?>">
                    <h3 class="block-title"><span><?= $category->name ?></span></h3>
                    <div class="post-overaly-style clearfix">
                        <div class="post-thumb">
                            <a href="#">
                                <img class="img-responsive" src="images/news/lifestyle/travel1.jpg" alt="" />
                            </a>
                        </div>

                        <div class="post-content">
                            <h2 class="post-title">
                                <a href="<?=Url::to(['/publications/view', 'id'=>$category->publications[0]->id])?>"><?= $category->publications[0]->title?></a>
                            </h2>
                            <div class="post-meta">
                                <span class="post-date"><?= $category->publications[0]->pub_date ?></span>
                            </div>
                        </div><!-- Post content end -->
                    </div><!-- Post Overaly Article end -->

                    <div class="list-post-block">
                        <ul class="list-post">
                            <li class="clearfix">
                                <div class="post-block-style post-float clearfix">
                                    <div class="post-thumb">
                                        <a href="#">
                                            <img class="img-responsive" src="images/news/lifestyle/travel2.jpg" alt="" />
                                        </a>
                                    </div><!-- Post thumb end -->

                                    <div class="post-content">
                                        <h2 class="post-title title-small">
                                            <a href="#">Early tourists choices to the sea of Maldives in fancy dress…</a>
                                        </h2>
                                        <div class="post-meta">
                                            <span class="post-date">Mar 13, 2017</span>
                                        </div>
                                    </div><!-- Post content end -->
                                </div><!-- Post block style end -->
                            </li><!-- Li 1 end -->

                            <li class="clearfix">
                                <div class="post-block-style post-float clearfix">
                                    <div class="post-thumb">
                                        <a href="#">
                                            <img class="img-responsive" src="images/news/lifestyle/travel3.jpg" alt="" />
                                        </a>
                                    </div><!-- Post thumb end -->

                                    <div class="post-content">
                                        <h2 class="post-title title-small">
                                            <a href="#">This Aeroplane that looks like a butt is the largest aircraf…</a>
                                        </h2>
                                        <div class="post-meta">
                                            <span class="post-date">Jan 11, 2017</span>
                                        </div>
                                    </div><!-- Post content end -->
                                </div><!-- Post block style end -->
                            </li><!-- Li 2 end -->

                            <li class="clearfix">
                                <div class="post-block-style post-float clearfix">
                                    <div class="post-thumb">
                                        <a href="#">
                                            <img class="img-responsive" src="images/news/lifestyle/travel4.jpg" alt="" />
                                        </a>
                                    </div><!-- Post thumb end -->

                                    <div class="post-content">
                                        <h2 class="post-title title-small">
                                            <a href="#">19 incredible photos from Disney's 'Star Wars' cruise algore</a>
                                        </h2>
                                        <div class="post-meta">
                                            <span class="post-date">Feb 19, 2017</span>
                                        </div>
                                    </div><!-- Post content end -->
                                </div><!-- Post block style end -->
                            </li><!-- Li 3 end -->
                        </ul><!-- List post end -->
                    </div><!-- List post block end -->
                </div><!-- Block end -->
            </div><!-- Travel Col end -->
            <?php } ?>


        </div><!-- Row end -->
    </div><!-- Container end -->
</section>
<!-- 2nd block end -->

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>